export const t = {
  brand: "Sutra",
  kicker: "Sutra",
  hero: "Changing your career is a full time job.",
  sub: "Automation allows you to apply more and fail more.",
  sub2:
    "Researching the market, customizing your applications and targeting the jobs where you actually have a chance is still difficult and energy intensive.",
  sub3: "We bring the best of both worlds, quality - at scale.",
  cta: "See it with Ana’s file",
  ctaOwn: "Use your own details",
  how: "What you can send",
  step1: "Your file",
  step1d:
    "Name, last role, and a CV with every job you have held. We rewrite that history onto one page for each listing. Local studio, EU remote, US market, and more.",
  step2: "A real listing",
  step2d:
    "Balkan, EU, and US roles in one run, scored against your stack. You pick a posting to attach proof to — not a spray list of five hundred tabs.",
  step3: "Sandbox proof",
  step3d:
    "A 48-hour project in a sandbox: files someone can inspect, copy into a repo, and send with the email for that job.",
  step4: "Tailored CV and pitch",
  step4d:
    "A one-page CV with every role from your file, rewritten for that company — plus a pitch you can say on a call.",
  whyTitle: "Quality — at scale",
  whyBody:
    "Automation lets you apply more and fail more. Researching the market, customizing applications, and targeting jobs where you actually have a chance is still slow. Sutra does that work with you: real listings, a CV rewritten for that role from your file, sandbox proof, and a pitch — quality at the pace of automation.",
  partners: "What happens when you click Run",
  footer: "Built at Grok Bot Serbia Hackathon · Belgrade",
  studio: "Studio",
  run: "Run agents",
  running: "Finding roles…",
  presets: "Try a sample person",
  name: "Name",
  city: "City",
  role: "Last role",
  company: "Company / context",
  years: "Years",
  skills: "Skills (comma)",
  languages: "Languages",
  tools: "Tools",
  situation: "Situation",
  target: "Target",
  bio: "What we should know",
  laid_off: "Laid off",
  student: "Student",
  pivot: "Pivoting",
  stuck: "Stuck",
  local_startup: "Local studio",
  eu_remote: "EU remote",
  freelance: "Fractional",
  web3: "Web3 / grant",
  us_market: "US market",
  trace: "What ran",
  market: "Market",
  proof: "Proof of work",
  monday: "Monday",
  emptyTrace: "Quiet so far. Click Run — Grok, Exa, Firecrawl, then Daytona work through your file.",
  sandbox: "Daytona",
  emptyMarket:
    "Roles land here with fit scores after you run. Each card builds a one-page CV from every job on your file, rewritten for that listing.",
  onePager: "CV for this role",
  onePagerBusy: "Tailoring CV…",
  onePagerNeedRun:
    "Run agents first. The tailored CV needs this listing plus the full work history from your uploaded CV.",
  onePagerEmail: "Email listing",
  onePagerMailto: "Email draft",
  onePagerCopy: "Copy email draft",
  onePagerCopied: "Copied",
  onePagerEmailHint:
    "Opens your mail app with a real address found on the listing. Attach the PDF from the other tab — Sutra does not send mail.",
  onePagerNoEmail:
    "No public hiring email on this listing. Email draft opens mailto with an empty To: — paste a recipient and attach the PDF. We will not invent an address or talk to Gmail for you.",
  onePagerSave: "Save PDF",
  onePagerSaving: "Saving…",
  onePagerSaved: "Saved the tailored CV PDF to your downloads.",
  onePagerShareDevice: "This device",
  onePagerSharing: "Sharing…",
  onePagerShared: "Shared the tailored CV.",
  onePagerCopiedShare: "Copied a short message about this role.",
  onePagerCopiedAndSaved:
    "Share sheet unavailable — copied a short message and downloaded the PDF.",
  onePagerShareAbort: "Share cancelled.",
  onePagerShareChannels: "Send this CV",
  onePagerGmail: "Gmail",
  onePagerShareHint:
    "Save PDF downloads the tailored CV. Email listing, Email draft, and Gmail open a compose window — mailto and Gmail compose cannot attach files from this page, so attach the PDF you saved. On phones that support it, This device can still share the PDF file.",
  onePagerGmailNote:
    "Saved the PDF and opened Gmail compose. Gmail’s compose link cannot attach files — attach the CV PDF from your downloads.",
  onePagerGmailNoteNoPdf:
    "Opened Gmail compose. It cannot attach files. Use Save PDF, then attach that file to the draft.",
  emptyProof: "Proof files appear here after the sandbox finishes.",
  emptyMonday: "Your week plan and pitch land here after you run.",
  pitchTitle: "Pitch coach",
  pitchHint: "Answer: “Go on, introduce yourself.”",
  pitchGo: "Score it",
  pitchListen: "Speak",
  stop: "Stop",
  rewrite: "Say it like this",
  elevator: "30-second intro",
  star: "STAR story",
  live: "live",
  demoAdapter: "offline",
  error: "Something broke. Try again.",
  required: "Name and role are required.",
  cvRequired: "Upload your CV first — we rewrite every role from that file onto one page for each job.",
  cvNeedHistory:
    "We could not read your work history. Upload a CV that lists each job (company, title, dates, what you did).",
  tour: "Tour",
  tourSkip: "Skip",
  tourNext: "Next",
  tourBack: "Back",
  tourDone: "Got it",
  tourValue: "What you get",
  tourStep: "Step",
  openListing: "open listing",
  savedCloud: "Saved to your Sutra cloud",
  savedDevice: "Saved on this device",
  savedCloudFail:
    "Couldn’t save to Sutra cloud. Your file is still on this device.",
  savedCloudLoadFail:
    "Couldn’t load Sutra cloud. Showing what’s on this device.",
  savedCloudMissingFn:
    "Sutra cloud has no save functions yet. Your file is only on this device.",
  savedCloudOffline:
    "Couldn’t reach Sutra cloud. Your file is still on this device.",
  photo: "CV photo",
  photoHint: "Optional headshot for the tailored CV. Shown as you uploaded it.",
  photoUpload: "Upload photo",
  photoReplace: "Replace",
  photoRemove: "Remove",
  photoBad: "Could not use that file. Try a JPEG or PNG under a few megabytes.",
  cv: "CV",
  cvHint:
    "Required. PDF or .txt/.md — Word .docx if it is a real export. We take every role from this file and rewrite them to fit one page for each job. You can still edit the fields after.",
  cvUpload: "Upload CV",
  cvReplace: "Replace",
  cvRemove: "Remove",
  cvUse: "Use this file",
  ingestOk: "Drafted from your file — edit anything that’s off, then Run.",
  ingestNeed: "Add a CV first.",
  wizardTitle: "A few questions so the search actually fits you",
  wizardLead:
    "Not a form wall. Click through. Your answers land on the dossier before agents hunt listings or rewrite your CV.",
  wizardNext: "Next",
  wizardBack: "Back",
  wizardSkipPhoto: "Skip photo",
  wizardReplay: "Start setup again",
  wizardSamples: "Skip this — try a sample person",
  wizardCvTitle: "Upload your CV",
  wizardCvBody:
    "PDF, .txt, .md, or a real Word .docx. We need every job on that file. You cannot continue until we can read the work history.",
  wizardStackTitle: "Skills, languages, and tools from your CV",
  wizardStackBody:
    "Only what we found on the file. Add or remove chips — these go on the tailored one-pager for each job.",
  wizardSkills: "Skills",
  wizardLanguages: "Languages",
  wizardTools: "Tools",
  wizardChipAdd: "Add",
  wizardChipPlaceholder: "Type, then Enter",
  wizardSituationTitle: "Where are you right now?",
  wizardSituationBody: "Pick the closest. Optional line if the label is too blunt.",
  wizardSituationNote: "Optional — one line",
  wizardTargetTitle: "Where do you want to work next?",
  wizardTargetBody: "This steers Exa and ranking — local studio, EU remote, US, freelance, or web3.",
  wizardTargetNote: "Optional — anything the chips miss",
  wizardCityTitle: "Which city should we treat as home base?",
  wizardWantTitle: "What do you want next?",
  wizardWantBody: "One or two sentences. This becomes the bio on your dossier and the tailored CV.",
  wizardWantPlaceholder:
    "I want an EU-remote backend seat where I own a service — not three months of courses after a layoff.",
  wizardYearsTitle: "How many years should we count?",
  wizardYearsBody: "Your CV did not make tenure obvious. Pick a band so seniority matching is not a guess.",
  wizardYears0: "Still getting started",
  wizardYears2: "1–2 years",
  wizardYears5: "3–5 years",
  wizardYears9: "6–9 years",
  wizardYears10: "10+ years",
  wizardPhotoTitle: "Photo for the CV? Optional.",
  wizardPhotoBody: "Headshot on the one-page tailored CV. Skip if you would rather send text only.",
  wizardReviewTitle: "Check the draft, then run",
  wizardReviewBody:
    "Name, last role, skills, languages, tools, and every job we took from your file. Light edits only — then agents use this dossier.",
  wizardExperience: "Work history from your CV",
  wizardDates: "Dates",
  wizardBullets: "Bullets",
  laid_offHint: "Team ended. I did not.",
  studentHint: "First real product role, not another tutorial.",
  pivotHint: "Same craft, different lane.",
  stuckHint: "Employed, going nowhere.",
  local_startupHint: "Belgrade / Novi Sad / Niš studios",
  eu_remoteHint: "EU product teams, remote-friendly",
  freelanceHint: "Fractional or contract, 90-day loops",
  web3Hint: "Grants, protocols, on-chain product",
  us_marketHint: "US or remote-US hiring",
} as const;

export type Copy = typeof t;
